#File generated by Hitachi Vantara Translator for package 'org.pentaho.di.trans.steps.addsequence' in locale 'it_IT'
#
#
#Fri Apr 09 12:28:30 CEST 2010
AddSequence.Name=Add sequence
AddSequence.Description=Get the next value from an sequence
AddSequence.Log.WriteRow=Scritta riga \#
AddSequence.Log.ConnectedDB=Connesso al database...
AddSequence.Exception.CouldNotFindNextValueForSequence=Impossibile trovare il successivo valore per la sequenza\: 
AddSequence.Log.ErrorInStep=A causa di un errore questo passo non pu\u00F2 continuare\: 
AddSequenceMeta.ErrorMessage.UnableToConnectDB=Impossibile connettersi al database per verificare lo stato della tabella.
AddSequence.Log.CouldNotConnectToDB=Il passo non \u00E8 riuscito a connettersi al database\: 
AddSequence.Log.TransformationCountersHashtableNotAllocated=Spiacente, tabella di hash dei contatori della trasformazione non allocata\! (errore interno)
AddSequenceMeta.Exception.UnableToReadStepInfo=Impossibile leggere le informazioni del passo dal repository per id_step\=
AddSequenceMeta.CheckResult.NoInputReceived.Title=Nessun input ricevuto dagli altri passi\!
AddSequence.Log.NeedToSelectSequence=Occorre una selezione per creare una sequenza od utilizzando un database oppure un contatore interno.
AddSequence.Exception.NoSpecifiedMethod=Nessun metodo \u00E8 specificato in questo passo\!
AddSequence.Log.ReadRow=Letta riga \#
AddSequenceMeta.ErrorMessage.NoConnectionDefined=Nessuna connessione definita in questo passo.
AddSequence.Log.CouldNotParseCounterValue=Il valore del contatore per {0} non pu\u00F2 essere analizzato, il valore originale \u00E8 {1} e diventa [{2}]. Errore\: {3}.
AddSequence.Exception.ErrorReadingSequence=Errore di lettura del successivo valore della sequenza [{0}] dal database
AddSequenceMeta.CheckResult.SequenceCouldNotBeFound.Title=La sequenza [{0}] non \u00E8 stata trovata
AddSequence.Log.CountersWithDifferentCharacteristics=Il contatore [{0}] \u00E8 definito pi\u00F9 volte con caratteristiche differenti.
AddSequenceMeta.Exception.ErrorLoadingStepInfo=Errore di caricamento delle informazioni del passo da XML
AddSequence.Log.LineNumber=linea n\u00B0 
AddSequenceMeta.Exception.UnableToSaveStepInfo=Impossibile salvare le informazioni del passo nel repository per id_step\=
AddSequenceMeta.CheckResult.SequenceExists.Title=La sequenza esiste.
AddSequenceMeta.CheckResult.StepIsReceving.Title=Il passo sta ricevendo informazioni dagli altri passi.
AddSequenceMeta.CheckResult.UnableToConnectDB.Title=Impossibile connettersi al database per verificare la sequenza a causa di un errore\: 
